@startuml
left to right direction
skinparam packageStyle rectangle

actor "Nurse" as NR

rectangle "PHMS - Nurse" {

  NR -- (View Lab Test Queue)
  NR -- (Update Lab Test Result)
  NR -- (Manage Profile)
  NR -- (Change Password)

  (View Lab Test Queue) ..> (Update Lab Test Result) : <<include>>
}

@enduml
