@startuml
left to right direction
skinparam packageStyle rectangle

actor "Veterinarian" as VT

rectangle "PHMS - Veterinarian" {

  VT -- (View Dashboard)
  VT -- (View EMR Queue)
  VT -- (Edit EMR Queue Notes)
  VT -- (Complete EMR)
  VT -- (Manage Medical Records\n Create / Update / Delete)
  VT -- (View Medical Record Detail)
  VT -- (Quick Submit Record)
  VT -- (Manage Prescriptions\n Create / Delete)
  VT -- (Manage Lab Requests\n Create / Cancel)
  VT -- (View Lab Request List)
  VT -- (Complete Appointment)
  VT -- (Manage Emergency\n Agree / Complete)
  VT -- (View Emergency Queue)
  VT -- (Request Leave)
  VT -- (View Staff Scheduling)

  (Manage Medical Records\n Create / Update / Delete) ..> (Manage Prescriptions\n Create / Delete) : <<include>>
  (Manage Medical Records\n Create / Update / Delete) ..> (View Medical Record Detail) : <<include>>
  (Quick Submit Record) ..> (Manage Medical Records\n Create / Update / Delete) : <<extend>>
}

@enduml
